apiVersion: v1
kind: ServiceAccount
metadata:
  name: extend-scheduler-sa
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: extend-scheduler
subjects:
  - kind: ServiceAccount
    name: extend-scheduler-sa
    namespace: kube-system
roleRef:
  kind: ClusterRole
  name: system:kube-scheduler
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: extend-scheduler-volume
subjects:
  - kind: ServiceAccount
    name: extend-scheduler-sa
    namespace: kube-system
roleRef:
  kind: ClusterRole
  name: system:volume-scheduler
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: scheduler-config2
  namespace: kube-system
data:
  scheduler.yaml: |
    apiVersion: kubescheduler.config.k8s.io/v1beta1
    kind: KubeSchedulerConfiguration
    clientConnection:
      kubeconfig: /etc/scheduler/scheduler.conf
    leaderElection:
      leaderElect: true
      leaseDuration: 15s
      renewDeadline: 10s
      retryPeriod: 2s
      resourceLock: leases
      resourceName: extend-scheduler
      resourceNamespace: kube-system
    percentageOfNodesToScore: 0
    podInitialBackoffSeconds: 1
    podMaxBackoffSeconds: 10
    profiles:
      - schedulerName: extend-scheduler
        plugins:
          score:
            enabled:
            - name: "DiskIO"
              weight: 100
            disabled:
            - name: "*"
        pluginConfig:
          - name: "DiskIO"
            args:
              ip: "http://10.112.0.85:38090"
              deviceName: "eth0"
              timeRange: 60
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: extend-scheduler
  namespace: kube-system
  labels:
    component: extend-scheduler
spec:
  selector:
    matchLabels:
      component: extend-scheduler
  template:
    metadata:
      labels:
        component: extend-scheduler
    spec:
      serviceAccountName: extend-scheduler-sa
      priorityClassName: system-cluster-critical
      volumes:
        - name: scheduler-config
          configMap:
            name: scheduler-config2
      containers:
        - name: scheduler
          image: hub.autox.tech/library/extend-scheduler:v0.5
          imagePullPolicy: IfNotPresent
          command:
            - ./scheduler
            - --config=/etc/scheduler/scheduler.yaml
            - --v=3
          resources:
            requests:
              cpu: "500m"
              memory: 4Gi
            limits:
              cpu: "500m"
              memory: 4Gi
          volumeMounts:
            - name: scheduler-config
              mountPath: /etc/scheduler1