apiVersion: kubescheduler.config.k8s.io/v1beta1
kind: KubeSchedulerConfiguration
clientConnection:
  kubeconfig: /etc/scheduler/scheduler.conf
leaderElection:
  leaderElect: true
  leaseDuration: 30s
  renewDeadline: 15s
  retryPeriod: 10s
  resourceLock: leases
  resourceName: extend-scheduler
  resourceNamespace: kube-system
percentageOfNodesToScore: 0
podInitialBackoffSeconds: 1
podMaxBackoffSeconds: 10
profiles:
  - schedulerName: extend-scheduler
    plugins:
      score:
        enabled:
        - name: "DiskIO"
          weight: 3
    pluginConfig:
      - name: "DiskIO"
        args:
          ip: "http://prometheus-scheduler.kube-system.svc.cluster.local:9190"
          #ip: "http://thanos-query.oam-system.svc.cluster.local:9090"
          deviceName: "eth0"
          timeRange: 60